version: "3.9"

services:
  db:
    build: ./db
    volumes:
      - sqlite_data:/app/data           # le fichier main.db sera ici
    networks: [internal]

  backend:
    build: ./backend
    environment:
      - JWT_SECRET=${JWT_SECRET:-devsecret}
      - DB_PATH=/data/main.db
    volumes:
      - sqlite_data:/app/data           # partage la base avec le service `db`
    ports:
      - "3000:3000"                 # API disponible sur localhost:3000
    depends_on: [db]
    networks: [internal]

  frontend:
    build: ./frontend
    ports:
      - "8080:80"                   # site servi sur localhost:8080
    depends_on: [backend]
    networks: [internal]

networks:
  internal:

volumes:
  sqlite_data: